version: '3'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "3008:8000"
    volumes:
      - ./:/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - APP_KEY=${APP_KEY}
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.4.6
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      #MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      # PMA_PORT: 3306
      # PMA_USER: ${DB_USERNAME:-root}
      # PMA_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - app_network
    depends_on:
      - mysql

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local