version: '3'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "3008:8000"
    volumes:
      - ./:/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_KEY=${APP_KEY}
      - APP_ENV=production
      - APP_DEBUG=false
